# config/meta.yml

# should exist in `app/assets/images/` twitter_account: "@product_twitter_account"
# required for Twitter Cards

meta_product_name: "BuildUp"
meta_title: "BuildUp pour tous les bons sacripants"
meta_description: "Let's move forward"
meta_image: "buildup.png"
twitter_account: "@SamyB23711680"
